const workProfileView = ({
    id,
    country,
    phone_number,
    city,
    cv_url,
    linkedin_url,
    github_url,
    featured_project,
    other_technologies_comment,
    ideal_work_comment,
    educational_level,
    relocation_option,
    dev_experience,
    design_experience,
    data_experience,
    gender,
    english_level,
    work_availability,
    education_status,
    visa,
    createdAt,
    updatedAt,
    Databases,
    DevLanguages,
    Tools,
    EducationExperiences,
    SoftSkills,
  }) => {
    return {
      success: true,
      message: "Work Profile obtained",
      data: {
        work_profile: {
          id,
          country,
          phoneNumber: phone_number,
          city,
          cvUrl: cv_url,
          linkedinUrl: linkedin_url,
          githubUrl: github_url,
          featuredProject: featured_project,
          otherTechnologiesComment: other_technologies_comment,
          idealWorkComment: ideal_work_comment,
          educationalLevel: educational_level,
          relocationOption: relocation_option,
          devExperience: dev_experience,
          designExperience: design_experience,
          dataExperience: data_experience,
          gender,
          englishLevel: english_level,
          workAvailability: work_availability,
          educationStatus: education_status,
          visa,
          createdAt,
          updatedAt,
          databases: Databases,
          devLanguages: DevLanguages,
          tools: Tools,
          educationExperiences: EducationExperiences,
          softSkills: SoftSkills,
        }
      }
    };
  };
  
  module.exports = workProfileView;